### ISSUE TITLE
Add documentation for new "Read Specific Line From File" sub-action

### ISSUE THREAD

**Issue by b-jazz** [Streamerbot/streamerbot-wiki#24]
I noticed a new sub-action for "Read Specific Line From File", but there is no associated documentation yet in: https://github.com/Streamerbot/streamerbot-wiki/tree/main/Sub-Actions/File

**Comment by Ik1497** [comment]
Added https://wiki.streamer.bot/en/Sub-Actions/File/Read-Specific-Line-From-File
