### ISSUE TITLE
Add Documentation & Example For Regex Match format

### ISSUE THREAD

**Issue by ickybodclay** [Streamerbot/streamerbot-wiki#3]
I was looking to add a regex check, but I noticed there are no examples of what format the regex string needs to be in or if there is any way to set the regex options (global, ignore case, multiline).

https://wiki.streamer.bot/en/Sub-Actions/Logic/If-Else

I am assuming that since there is C# script report, that this is written in C# and supports the following:
https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=net-6.0

Is this correct?  Also is there any current way to set the options?

Also thanks again for making this tool, love Streamer.bot <3

**Comment by GoWMan813** [comment]
Sorry, I am just now seeing this.  SB is built on the .NET Framework 4.7.2 so it should support https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=netframework-4.7.2

As far as regex options I am unsure as I don't use regex myself much but I'm sure someone in the Discord server would have that answer.

The best place to get quick help would be the Discord server as we don't always review the repo on a regular basis.  I will see about maybe adding some Regex documentation to the docs though.  I could see where that may be helpful in some use cases.

**Comment by ikeman2003** [comment]
#27 Added some info relating to RegEx
